"""int8 quantization for the ESP32 export path.

Scheme (mirrored exactly by the C engine in esp32/main/a2lm.c):

* Linear weights  -> int8, one float scale per OUTPUT channel (row).
      wq[i][j] = round(w[i][j] / scale[i]),  scale[i] = max_j |w[i][j]| / 127
      y[i] = scale[i] * (sum_j wq[i][j] * x[j]) + bias[i]      (float x)
* Embeddings      -> int8, one float scale per ROW (one row per token/pos).
* LayerNorm g/b   -> kept as float32 (tiny: 2 * dim per norm).
* All biases      -> float32.

Activations stay float32 in the C engine (only weights are quantized), which
keeps accuracy high while shrinking flash usage to ~1 byte/parameter.

Output: two C files
  esp32/main/weights.h       -> config macros + extern declarations
  esp32/main/weights_data.h  -> the actual arrays + layer table
(weights_data.h is included ONLY by a2lm.c so the data lives in one TU.)
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Tuple

import torch

from .model import A2LM


def quantize_per_row(w: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    """Quantize a (rows, cols) matrix to int8 with per-row float scales."""
    w = w.detach().float()
    scale = w.abs().amax(dim=1) / 127.0
    scale = torch.clamp(scale, min=1e-12)
    wq = torch.round(w / scale.unsqueeze(1)).clamp(-128, 127).to(torch.int8)
    return wq, scale


def _add(decls: List[str], defs: List[str], name: str, t: torch.Tensor,
         ctype: str, per_line: int = 24) -> None:
    """Emit an extern declaration (header) + definition (data file)."""
    decls.append(f"extern const {ctype} {name}[{t.numel()}];")
    if ctype == "int8_t":
        defs += format_array(name, t, per_line)
    else:
        defs += format_float_array(name, t, per_line)


def format_array(name: str, t: torch.Tensor, per_line: int = 24) -> List[str]:
    """Emit a C const array definition from a tensor."""
    flat = t.detach().reshape(-1).tolist()
    lines = [f"const int8_t {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), per_line):
        chunk = ", ".join(str(int(v)) for v in flat[i : i + per_line])
        lines.append("    " + chunk + ",")
    lines.append("};")
    return lines


def format_float_array(name: str, t: torch.Tensor, per_line: int = 16) -> List[str]:
    flat = t.detach().reshape(-1).tolist()
    lines = [f"const float {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), per_line):
        chunk = ", ".join(f"{v:.9g}f" for v in flat[i : i + per_line])
        lines.append("    " + chunk + ",")
    lines.append("};")
    return lines


def export_model_to_header(
    model: A2LM, out_path: str | Path, tokenizer_type: str = "byte"
) -> Dict[str, int]:
    """Quantize ``model`` and write esp32/main/weights.h + weights_data.h.

    Returns metadata (params, bytes, ...). Requires a byte-level tokenizer
    (vocab 256) because the on-device encoder is a plain UTF-8 byte map.
    """
    cfg = model.cfg
    if tokenizer_type != "byte":
        raise ValueError(
            "ESP32 export requires the byte tokenizer (vocab 256); "
            f"checkpoint uses {tokenizer_type!r}"
        )
    if cfg.vocab_size != 256:
        raise ValueError(
            f"ESP32 export requires vocab_size 256 (byte tokens), got {cfg.vocab_size}"
        )

    sd = model.state_dict()
    decls: List[str] = []    # weights.h: macros + extern declarations
    defs: List[str] = []     # weights_data.h: arrays + layer table
    for out in (decls, defs):
        out.append("/* Auto-generated by scripts/export_esp32.py - DO NOT EDIT. */")
        out.append(f"/* A2LM-ESP weights, int8, tokenizer=byte, "
                   f"{model.num_parameters():,} params */")
        out.append("")
    defs.append("#ifndef A2LM_WEIGHTS_DATA_H")
    defs.append("#define A2LM_WEIGHTS_DATA_H")
    defs.append('#include "weights.h"')
    defs.append("")
    for out in (decls, defs):
        out.append(f"#define A2LM_VOCAB {cfg.vocab_size}")
        out.append(f"#define A2LM_CTX {cfg.context_length}")
        out.append(f"#define A2LM_DIM {cfg.embedding_dim}")
        out.append(f"#define A2LM_LAYERS {cfg.num_layers}")
        out.append(f"#define A2LM_HEADS {cfg.num_heads}")
        out.append(f"#define A2LM_HEAD_DIM (A2LM_DIM / A2LM_HEADS)")
        out.append(f"#define A2LM_FFN {cfg.ffn_dim}")
        out.append("")
    decls.append("#ifndef A2LM_WEIGHTS_H")
    decls.append("#define A2LM_WEIGHTS_H")
    decls.append("#ifdef __cplusplus")
    decls.append('extern "C" {')
    decls.append("#endif")
    decls.append("")

    # --- embeddings (per-row scales) ---------------------------------------
    wq, s = quantize_per_row(sd["token_embedding.weight"])
    _add(decls, defs, "A2LM_TOKEN_EMB", wq, "int8_t")
    _add(decls, defs, "A2LM_TOKEN_EMB_SCALE", s, "float")
    wq, s = quantize_per_row(sd["position_embedding.weight"])
    _add(decls, defs, "A2LM_POS_EMB", wq, "int8_t")
    _add(decls, defs, "A2LM_POS_EMB_SCALE", s, "float")
    defs.append("")

    # --- per-layer tensors --------------------------------------------------
    for i in range(cfg.num_layers):
        pre = f"L{i}"
        wq, s = quantize_per_row(sd[f"blocks.{i}.attn.qkv.weight"])
        _add(decls, defs, f"A2LM_W_{pre}_QKV", wq, "int8_t")
        _add(decls, defs, f"A2LM_S_{pre}_QKV", s, "float")
        wq, s = quantize_per_row(sd[f"blocks.{i}.attn.out_proj.weight"])
        _add(decls, defs, f"A2LM_W_{pre}_OUT", wq, "int8_t")
        _add(decls, defs, f"A2LM_S_{pre}_OUT", s, "float")
        _add(decls, defs, f"A2LM_LN1_G_{pre}", sd[f"blocks.{i}.ln1.weight"], "float")
        _add(decls, defs, f"A2LM_LN1_B_{pre}", sd[f"blocks.{i}.ln1.bias"], "float")
        wq, s = quantize_per_row(sd[f"blocks.{i}.ffn.net.0.weight"])
        _add(decls, defs, f"A2LM_W_{pre}_UP", wq, "int8_t")
        _add(decls, defs, f"A2LM_S_{pre}_UP", s, "float")
        _add(decls, defs, f"A2LM_B_{pre}_UP", sd[f"blocks.{i}.ffn.net.0.bias"], "float")
        wq, s = quantize_per_row(sd[f"blocks.{i}.ffn.net.2.weight"])
        _add(decls, defs, f"A2LM_W_{pre}_DOWN", wq, "int8_t")
        _add(decls, defs, f"A2LM_S_{pre}_DOWN", s, "float")
        _add(decls, defs, f"A2LM_B_{pre}_DOWN", sd[f"blocks.{i}.ffn.net.2.bias"], "float")
        _add(decls, defs, f"A2LM_LN2_G_{pre}", sd[f"blocks.{i}.ln2.weight"], "float")
        _add(decls, defs, f"A2LM_LN2_B_{pre}", sd[f"blocks.{i}.ln2.bias"], "float")
        defs.append("")

    # --- final norm + (tied) head ------------------------------------------
    _add(decls, defs, "A2LM_LN_F_G", sd["ln_f.weight"], "float")
    _add(decls, defs, "A2LM_LN_F_B", sd["ln_f.bias"], "float")
    defs.append("")

    # --- layer table (indexed by the C engine, layer count agnostic) -------
    decls.append("typedef struct {")
    decls.append("    const int8_t *qkv, *out, *up, *down;")
    decls.append("    const float *qkv_s, *out_s, *up_s, *down_s;")
    decls.append("    const float *ln1_g, *ln1_b, *ln2_g, *ln2_b;")
    decls.append("    const float *up_b, *down_b;")
    decls.append("} A2LMLayerDef;")
    decls.append("")
    decls.append(f"extern const A2LMLayerDef A2LM_LAYER_TABLE[{cfg.num_layers}];")
    decls.append("")
    decls.append("#ifdef __cplusplus")
    decls.append("}")
    decls.append("#endif")
    decls.append("")
    decls.append("#endif /* A2LM_WEIGHTS_H */")

    defs.append(f"const A2LMLayerDef A2LM_LAYER_TABLE[{cfg.num_layers}] = {{")
    for i in range(cfg.num_layers):
        defs.append(f"    {{ A2LM_W_L{i}_QKV,  A2LM_W_L{i}_OUT,  A2LM_W_L{i}_UP,   A2LM_W_L{i}_DOWN,")
        defs.append(f"      A2LM_S_L{i}_QKV,  A2LM_S_L{i}_OUT,  A2LM_S_L{i}_UP,   A2LM_S_L{i}_DOWN,")
        defs.append(f"      A2LM_LN1_G_L{i},  A2LM_LN1_B_L{i},  A2LM_LN2_G_L{i},  A2LM_LN2_B_L{i},")
        defs.append(f"      A2LM_B_L{i}_UP,   A2LM_B_L{i}_DOWN }},")
    defs.append("};")
    defs.append("")

    # --- byte accounting (weights only; scales/biases are tiny floats) ------
    # dedupe by data_ptr: the tied LM head shares the token-embedding tensor
    seen: set[int] = set()
    int8_bytes = 0
    for name, p in sd.items():
        if name.endswith(".weight") and "ln" not in name and p.data_ptr() not in seen:
            seen.add(p.data_ptr())
            int8_bytes += p.numel()
    for out in (decls, defs):
        out.append(f"#define A2LM_INT8_WEIGHT_BYTES {int8_bytes}")
        out.append(f"#define A2LM_TOTAL_PARAMS {model.num_parameters()}")
    defs.append("")
    defs.append("#endif /* A2LM_WEIGHTS_DATA_H */")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    data_path = out_path.with_name("weights_data.h")
    out_path.write_text("\n".join(decls), encoding="utf-8")
    data_path.write_text("\n".join(defs), encoding="utf-8")
    return {"params": model.num_parameters(), "int8_bytes": int8_bytes,
            "header": str(out_path), "data_header": str(data_path)}