/* Host-side test harness for the A2LM-ESP C engine (no ESP-IDF needed).
 *
 * Build:
 *     gcc -O2 -I../main ../main/a2lm.c main.c -lm -o host_a2lm
 *
 * Modes:
 *     host_a2lm logits   <prompt>          -> prints "LOGITS v0 v1 ... v255"
 *     host_a2lm generate <prompt> [temp]   -> prints generated bytes
 *
 * Used by scripts/check_esp32_parity.py to verify the C engine against the
 * PyTorch reference.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../main/a2lm.h"

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: %s logits|generate <prompt> [temperature]\n", argv[0]);
        return 2;
    }
    const char *mode = argv[1];
    const uint8_t *prompt = (const uint8_t *)argv[2];
    size_t n = strlen(argv[2]);
    if (n > A2LM_CTX) n = A2LM_CTX;

    if (strcmp(mode, "logits") == 0) {
        float logits[A2LM_VOCAB];
        a2lm_logits(prompt, n, logits);
        printf("LOGITS");
        for (int i = 0; i < A2LM_VOCAB; i++) printf(" %.8g", logits[i]);
        printf("\n");
        return 0;
    }

    if (strcmp(mode, "generate") == 0) {
        float temp = argc > 3 ? (float)atof(argv[3]) : 0.0f;
        uint8_t out[256];
        uint32_t rng = 12345u;
        /* greedy (top_k=1) for parity checks; plain sampling when temp > 0 */
        int top_k = temp > 0.0f ? 0 : 1;
        size_t n_out = a2lm_generate(prompt, n, 200, temp, top_k,
                                     &rng, out);
        fwrite(out, 1, n_out, stdout);
        printf("\n");
        return 0;
    }

    fprintf(stderr, "unknown mode %s\n", mode);
    return 2;
}