/* Auto-generated by scripts/export_esp32.py - DO NOT EDIT. */
/* A2LM-ESP weights, int8, tokenizer=byte, 34,432 params */

#define A2LM_VOCAB 256
#define A2LM_CTX 32
#define A2LM_DIM 32
#define A2LM_LAYERS 2
#define A2LM_HEADS 2
#define A2LM_HEAD_DIM (A2LM_DIM / A2LM_HEADS)
#define A2LM_FFN 128

#ifndef A2LM_WEIGHTS_H
#define A2LM_WEIGHTS_H
#ifdef __cplusplus
extern "C" {
#endif

extern const int8_t A2LM_TOKEN_EMB[8192];
extern const float A2LM_TOKEN_EMB_SCALE[256];
extern const int8_t A2LM_POS_EMB[1024];
extern const float A2LM_POS_EMB_SCALE[32];
extern const int8_t A2LM_W_L0_QKV[3072];
extern const float A2LM_S_L0_QKV[96];
extern const int8_t A2LM_W_L0_OUT[1024];
extern const float A2LM_S_L0_OUT[32];
extern const float A2LM_LN1_G_L0[32];
extern const float A2LM_LN1_B_L0[32];
extern const int8_t A2LM_W_L0_UP[4096];
extern const float A2LM_S_L0_UP[128];
extern const float A2LM_B_L0_UP[128];
extern const int8_t A2LM_W_L0_DOWN[4096];
extern const float A2LM_S_L0_DOWN[32];
extern const float A2LM_B_L0_DOWN[32];
extern const float A2LM_LN2_G_L0[32];
extern const float A2LM_LN2_B_L0[32];
extern const int8_t A2LM_W_L1_QKV[3072];
extern const float A2LM_S_L1_QKV[96];
extern const int8_t A2LM_W_L1_OUT[1024];
extern const float A2LM_S_L1_OUT[32];
extern const float A2LM_LN1_G_L1[32];
extern const float A2LM_LN1_B_L1[32];
extern const int8_t A2LM_W_L1_UP[4096];
extern const float A2LM_S_L1_UP[128];
extern const float A2LM_B_L1_UP[128];
extern const int8_t A2LM_W_L1_DOWN[4096];
extern const float A2LM_S_L1_DOWN[32];
extern const float A2LM_B_L1_DOWN[32];
extern const float A2LM_LN2_G_L1[32];
extern const float A2LM_LN2_B_L1[32];
extern const float A2LM_LN_F_G[32];
extern const float A2LM_LN_F_B[32];
typedef struct {
    const int8_t *qkv, *out, *up, *down;
    const float *qkv_s, *out_s, *up_s, *down_s;
    const float *ln1_g, *ln1_b, *ln2_g, *ln2_b;
    const float *up_b, *down_b;
} A2LMLayerDef;

extern const A2LMLayerDef A2LM_LAYER_TABLE[2];

#ifdef __cplusplus
}
#endif

#endif /* A2LM_WEIGHTS_H */
#define A2LM_INT8_WEIGHT_BYTES 33792
#define A2LM_TOTAL_PARAMS 34432